### ISSUE TITLE
ITK build during developer installation fails on Linux with GCC 15

### ISSUE THREAD

**Issue by srmarcballestero** [OpenGATE/opengate#1000]
Hi,

I have been trying to install OpenGATE in developer mode in my machine, see details below:

- **OS:** Fedora Linux 43 (Workstation Edition) on Linux 6.19.11
- **gcc/g++:** 15.2.1 20260123 (Red Hat 15.2.1-7)
- **cmake:** 3.31.11
- **python:** 3.14.3

When building ITK 5.2.1 from source, based on the `cmake` command provided in the documentation:
```bash
cmake -DCMAKE_CXX_FLAGS=-std=c++17 \
      -DBUILD_TESTING=OFF \
      ../ITK
make -j 32
```
I came across a set of compile errors apparently related to GCC 13+ stricter header hygiene and C standard changes. Specifically: missing `#include <cstdint>` in some modules and function pointers that are no longer valid under C23.

My workaround has been to add the flags `-DCMAKE_CXX_FLAGS="-std=c++17 -include cstdint"` and `-DCMAKE_C_FLAGS="-std=gnu11"` to the `cmake` command to allow for flawless compilation.

Just FYI, maybe worth adding to the documentation :)

Cheers,

Marc

**Comment by nkrah** [comment]
Thanks Marc for reporting. So that is actually an ITK issue then. Have you, by chance, looked at the ITK Discourse if anyone else reported similar issues?

**Comment by SimonRit** [comment]
Why don't you build with the latest ITK? 5.2.1 is 5 years old... I'm sure these issues have been addressed since.

**Comment by srmarcballestero** [comment]
Hi @nkrah @SimonRit 
 
There's the following issue regarding the missing headers in the ITK repo (Apr. 2024): https://github.com/InsightSoftwareConsortium/ITK/issues/4600.
 
I have now checked which ITK version the bundled OpenGATE PyPI package (user install) uses, and I see it is 5.4.4. Building this version on my system solved the missing `cstdint` error, but the issue with the C standard is still there:
```
[ 87%] Building C object Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/volume_io/MNI_formats/gen_xfs.c.o
/home/marc/Projects/opengate/external/itk/itk-v5.4.4-src/Modules/ThirdParty/MINC/src/libminc/libcommon/ParseArgv.c: In function ‘ParseArgv’:
/home/marc/Projects/opengate/external/itk/itk-v5.4.4-src/Modules/ThirdParty/MINC/src/libminc/libcommon/ParseArgv.c:320:15: error: too many arguments to function ‘handlerProc’; expected 0, have 3
  320 |          if ((*handlerProc)(infoPtr->dst, infoPtr->key,
      |              ~^~~~~~~~~~~~~ ~~~~~~~~~~~~
/home/marc/Projects/opengate/external/itk/itk-v5.4.4-src/Modules/ThirdParty/MINC/src/libminc/libcommon/ParseArgv.c:330:18: error: too many arguments to function ‘handlerProc’; expected 0, have 4
  330 |          argc = (*handlerProc)(infoPtr->dst, infoPtr->key,
      |                 ~^~~~~~~~~~~~~ ~~~~~~~~~~~~

```
The issue seems to be related to `libminc`. I wasn't able to find any discussion specifically about this. The workaround is to add `-DCMAKE_C_FLAGS="-std=gnu11"` to the `cmake` command.
 
Cheers,
Marc

**Comment by djboersma** [comment]
> Why don't you build with the latest ITK? 5.2.1 is 5 years old... I'm sure these issues have been addressed since.

The opengate developer guide actually still advertises 5.2.1, maybe that guide should be updated (I myself used 5.4.4 this week, compiled out of the box)? I'm also queasy about recommending setting `CMAKE_CXX_FLAGS="-std=c++17"`, wouldn't `CMAKE_CXX_STANDARD=17` be better (less dependent on compiler/platform details)? I just submitted a PR with some cleanups in the docs, I could just add these changes.
